<xsl:stylesheet version="1.0"
	xmlns:xsl = "http://www.w3.org/1999/XSL/Transform">

<xsl:variable name="IDS_BPT_COLON">Business Process Test:</xsl:variable>
<xsl:variable name="IDS_BC_COLON">Business Component:</xsl:variable>
<xsl:variable name="IDS_TEST_COLON">Test: </xsl:variable>
<xsl:variable name="IDS_INPUT_PARAMETERS">Input Parameters </xsl:variable>
<xsl:variable name="IDS_VALUE">Value</xsl:variable>
<xsl:variable name="IDS_OUTPUT_PARAMETERS">Output Parameters </xsl:variable>
<xsl:variable name="IDS_STEP_NAME_COLON">Step Name: </xsl:variable>
<xsl:variable name="IDS_OBJECT">Object</xsl:variable>
<xsl:variable name="IDS_DETAILS">Details</xsl:variable>
<xsl:variable name="IDS_RESULT">Result</xsl:variable>
<xsl:variable name="IDS_TIME">Time</xsl:variable>
<xsl:variable name="IDS_RESULTS_SUMMARY"> Results Summary</xsl:variable>
<xsl:variable name="IDS_ACTION_COLON">Action: </xsl:variable>
<xsl:variable name="IDS_RUN_STARTED_COLON">Run started: </xsl:variable>
<xsl:variable name="IDS_RUN_ENDED_COLON">Run ended: </xsl:variable>
<xsl:variable name="IDS_RESULT_COLON">Result: </xsl:variable>
<xsl:variable name="IDS_STATUS">Status </xsl:variable>
<xsl:variable name="IDS_TIMES">Times</xsl:variable>
<xsl:variable name="IDS_PASSED">Passed</xsl:variable>
<xsl:variable name="IDS_FAILED">Failed</xsl:variable>
<xsl:variable name="IDS_WARNING">Warning</xsl:variable>
<xsl:variable name="IDS_DONE">Done</xsl:variable>
<xsl:variable name="IDS_WARNINGS">Warnings</xsl:variable>
<xsl:variable name="IDS_ITERATION">Iteration </xsl:variable>
<xsl:variable name="IDS_OBJECT_TAB">Object	</xsl:variable>
<xsl:variable name="IDS_DETAILS_TAB">Details	</xsl:variable>
<xsl:variable name="IDS_RESULT_TAB">Result	</xsl:variable>
<xsl:variable name="IDS_TIME_TAB">Time	</xsl:variable>
<xsl:variable name="IDS_RESULTS_NAME_COLON">Results name : </xsl:variable>
<xsl:variable name="IDS_TIME_ZONE_COLON">Time Zone:  </xsl:variable>
<xsl:variable name="IDS_TEST_VER_COLON">Test version: </xsl:variable>
<xsl:variable name="IDS_TEST_SET_COLON">Test set: </xsl:variable>
<xsl:variable name="IDS_PRODUCT_VERSION_COLON">Product version: </xsl:variable>
<xsl:variable name="IDS_HOST_NAME_COLON">Host Name: </xsl:variable>
<xsl:variable name="IDS_OS_COLON">Operating System: </xsl:variable>
<xsl:variable name="IDS_QC_SERVER_COLON">Quality Center Server: </xsl:variable>
<xsl:variable name="IDS_QC_PROJECT_COLON">Quality Center Project: </xsl:variable>
<xsl:variable name="IDS_TEST_INSTANCE_COLON">Test instance: </xsl:variable>
<xsl:variable name="IDS_ITERATION_NUMBER">Iteration # </xsl:variable>
<xsl:variable name="IDS_RESULTS">Results</xsl:variable>
<xsl:variable name="IDS_REPORT"> Report</xsl:variable>
<xsl:variable name="IDS_TEST_ITERATION">Test Iteration </xsl:variable>
<xsl:variable name="IDS_NAME">Name</xsl:variable>
<xsl:variable name="IDS_END_COLON">End: </xsl:variable>
<xsl:variable name="IDS_BC">Business Component </xsl:variable>
<xsl:variable name="IDS_STEP">Step </xsl:variable>
<xsl:variable name="IDS_PRODUCT_NAME_COLON">Product name: </xsl:variable>
<xsl:variable name="IDS_SUMMARY_COLON"> Summary:</xsl:variable>
<xsl:variable name="IDS_UPDATE_RUN_COLON"> This test was run using the following Update Run options:</xsl:variable>
<xsl:variable name="IDS_UPDATE_TO_PROPS"> Update test object descriptions</xsl:variable>
<xsl:variable name="IDS_UPDATE_CP_OV_PROPS"> Update checkpoint properties</xsl:variable>
<xsl:variable name="IDS_UPDATE_ACTIVE_SCREEN"> Update Active Screen images and values</xsl:variable>

</xsl:stylesheet>
